name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses:
          actions/checkout@v3

          # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_FIRE_BASE_API_KEY=$REACT_APP_FIRE_BASE_API_KEY" >> .env
          echo "REACT_APP_FIRE_BASE_APP_ID=$REACT_APP_FIRE_BASE_APP_ID" >> .env
          echo "REACT_APP_FIRE_BASE_AUTH_DOMAIN=$REACT_APP_FIRE_BASE_AUTH_DOMAIN" >> .env
          echo "REACT_APP_FIRE_BASE_MESSAGING_SENDER_ID=$REACT_APP_FIRE_BASE_MESSAGING_SENDER_ID" >> .env
          echo "REACT_APP_FIRE_BASE_PROJECT_ID=$REACT_APP_FIRE_BASE_PROJECT_ID" >> .env
          echo "REACT_APP_FIRE_BASE_STORAGE_BUCKET=$REACT_APP_FIRE_BASE_STORAGE_BUCKET" >> .env
        env:
          REACT_APP_FIRE_BASE_API_KEY: ${{ secrets.REACT_APP_FIRE_BASE_API_KEY }}
          REACT_APP_FIRE_BASE_APP_ID: ${{ secrets.REACT_APP_FIRE_BASE_APP_ID }}
          REACT_APP_FIRE_BASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIRE_BASE_AUTH_DOMAIN }}
          REACT_APP_FIRE_BASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIRE_BASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIRE_BASE_PROJECT_ID: ${{ secrets.REACT_APP_FIRE_BASE_PROJECT_ID }}
          REACT_APP_FIRE_BASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIRE_BASE_STORAGE_BUCKET }}

      - run: npm i && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUIZ_39D99 }}"
          channelId: live
          projectId: quiz-39d99
